### ISSUE TITLE
Add Event emissions for various actions

### ISSUE THREAD

**Issue by apbendi** [ScopeLift/l2-flexible-voting#29]
We should add logical event emissions with useful data across all contracts in the system. Anytime an action is being taken, we should emit and properly document a useful event.

**Comment by wildmolasses** [comment]
Thinking of this as event scheme:

# Core contracts

## L1VotePool.sol

### `_castVote`

- `CastVote(uint proposalId, uint voteAgainst, uint voteFor, uint voteAbstain)`

## L2GovernorMetadata.sol

### `_addProposal`
- `ProposalAdded(uint proposalId, uint voteStart, uint voteEnd)`

## L2VoteAggregator.sol

### `initialize`
- Emit on initialize? In general, consider using openzeppelin-contracts/contracts/proxy/utils/Initializable.sol, or overkill?

### `castVote`
- (already exists) `VoteCast(address indexed sender, uint proposalId, uint support, uint weight)`

### `bridgeVote`
- `VoteBridged(uint proposalId, uint voteAgainst, uint voteFor, uint voteAbstain)`

# Wormhole contracts

## WormholeL1ERC20Bridge.sol

### `initialize`
- Emit on initialize?

### `deposit`
- `Deposit(address indexed sender, address indexed targetAddress, uint targetChain, uint256 amount, uint deliveryCost)`

### `_withdraw`
- `Withdraw(address indexed account, uint amount)`
  - should we pull more data from the message so we can emit sourceChain, sourceAddress, etc? If we do, should this event be emitted in `_receiveWithdrawalWormholeMessages` instead?

## WormholeL1GovernorMetadataBridge.sol

### `initialize`
- Emit on initialize?

### `bridgeProposalMetadata`
- `BridgeProposalMetadata(uint proposalId, uint voteStart, uint voteEnd, uint targetChain, uint cost, address targetGovernor)`

## WormholeL1VotePool.sol

No events needed; `L1VotePool:_castVote` already emits `VoteCast`

## WormholeL2ERC20.sol

### `initialize`
- Emit on initialize?

### `l1Unlock`
- `L1Unlock(address indexed account, address indexed targetAddress, uint256 amount, uint targetChain, address targetToken)`

## WormholeL2GovernorMetadata.sol

No events needed; `L2GovernorMetadata:_addProposal` already emits `ProposalAdded`

## WormholeL2VoteAggregator.sol

No events needed; `L2VoteAggregator:bridgeVote` already emits `VoteBriged`

## WormholeReceiver.sol

### `setRegisteredSender`
- `RegisteredSenderSet(uint16 sourceChain, indexed address sourceAddress)`

### `receiveWormholeMessages`

This is a virtual method, but we could define an event in `WormholeReceiver` that we expect all descendants to emit.

- `WormholeMessageReceived(uint16 sourceChain, address sourceAddress, bytes message)`

**Comment by mds1** [comment]
> Thinking of this as event scheme:
> 
> ## Core contracts
> 
> ### L1VotePool.sol
> 
> #### `_castVote`
> 
> - `CastVote(uint indexed proposalId, uint voteAgainst, uint voteFor, uint voteAbstain)`

For reference, what OZ uses in their Governor is [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f0316a4cefc5526b9e052e77b5c29b6a715d4f98/contracts/governance/IGovernor.sol#L142C6-L142C6)
```solidity
event VoteCast(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason);
```

We might want to mirror that more closely and do 

```solidity
event VoteCast(address indexed caller, uint proposalId, uint voteAgainst, uint voteFor, uint voteAbstain);
```

Maybe useful to know who called it? Otherwise can remove it. Also is there one `L1VotePool` per governor, or is it a singleton? If a singleton we should include the governor address

Consider indexing `proposalId` in all of these events, not familiar enough with the arch to know if ability to filter events by proposal ID is useful

> ### L2GovernorMetadata.sol
> 
> #### `_addProposal`
> - `ProposalAdded(uint indexed proposalId, uint voteStart, uint voteEnd)`

This means a proposal that already was created on L1 had it's metadata added to the L2 contract? Perhaps the full set of proposal metadata should be included, e.g. proposer, targets, etc.? Or if we only add the required metadata instead of all of it, then the current version makes sense. [OZ version](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f0316a4cefc5526b9e052e77b5c29b6a715d4f98/contracts/governance/IGovernor.sol#L110C2-L120) for reference.

Similar question about singleton / including governor address

> ### L2VoteAggregator.sol
> 
> #### `initialize`
> - Emit on initialize? In general, consider using openzeppelin-contracts/contracts/proxy/utils/Initializable.sol, or overkill?

What happens in initialize vs. construction? Since we're on L2, execution is cheap so we prob don't need minimal proxies. The constructor/initializer should emit "regular" events, such as setting an owner, etc.
 
> #### `castVote`
> - (already exists) `VoteCast(address indexed sender, uint indexed proposalId, uint support, uint weight)`
> 
> #### `bridgeVote`
> - `VoteBridged(uint proposalId, uint voteAgainst, uint voteFor, uint voteAbstain)`

Same comments as the L1 _castVoteabove here, and consider adding the caller to `VoteBridged`

> ## Wormhole contracts
> 
> ### WormholeL1ERC20Bridge.sol
> 
> #### `initialize`
> - Emit on initialize?

Same answer as above intialize

> #### `deposit`
> - `Deposit(address indexed sender, address indexed targetAddress, uint targetChain, uint256 amount, uint deliveryCost)`

Seems good, consider indexing the targetChain
 
> #### `_withdraw`
> - `Withdraw(address indexed account, uint amount)`
>   - should we pull more data from the message so we can emit sourceChain, sourceAddress, etc? If we do, should this event be emitted in `_receiveWithdrawalWormholeMessages` instead?

Gut reaction is that if you have the data available, emitting it may be useful and should be cheap, so may as well

For everything below, no comments aside from what's already been mentioned:
- Consider always indexing chains and token addresses (e.g. `L1Unlock` does not index `targetToken`)
- Consider emitting the caller if that is useful

> ### WormholeL1GovernorMetadataBridge.sol
> 
> #### `initialize`
> - Emit on initialize?
> 
> #### `bridgeProposalMetadata`
> - `BridgeProposalMetadata(uint16 indexed targetChain, address indexed targetGovernor, uint indexed proposalId, uint voteStart, uint voteEnd, uint cost)`
> 
> ### WormholeL1VotePool.sol
> 
> No events needed; `L1VotePool:_castVote` already emits `VoteCast`
> 
> ### WormholeL2ERC20.sol
> 
> #### `initialize`
> - Emit on initialize?
> 
> #### `l1Unlock`
> - `L1Unlock(address indexed account, address indexed targetAddress, uint256 amount, uint16 targetChain, address targetToken)`
> 
> ### WormholeL2GovernorMetadata.sol
> 
> No events needed; `L2GovernorMetadata:_addProposal` already emits `ProposalAdded`
> 
> ### WormholeL2VoteAggregator.sol
> 
> No events needed; `L2VoteAggregator:bridgeVote` already emits `VoteBridged`
> 
> ### WormholeReceiver.sol
> 
> #### `setRegisteredSender`
> - `RegisteredSenderSet(uint16 indexed sourceChain, indexed address sourceAddress)`
> 
> #### `receiveWormholeMessages`
> 
> This is a virtual method, but we could define an event in `WormholeReceiver` that we expect all descendants to emit:
> 
> - `WormholeMessageReceived(uint16 indexed sourceChain, address indexed sourceAddress, bytes message)`
